# -*- coding: utf-8 -*-
"""TD1 - M1.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1msBlBYvcgB4yKlMu_MElkGLMH_nzVFdV
"""

#Exercice1

x = 5
y = 1
z = 2.5

print (x + z + y)
print (x - z - y)
print (x * y * z)
print (x ** z)
print (z%x)
print (x // z)

#Exercice2

s = "Luis"
t = " aime le foot"
p = " !"
print (s + t)
print (s + t + p*3)
len(s + t + p*3)

#Exercice3


a = 2
b = 10
c = "On est en 2020"
d = "d'ici 10 ans on sera en 2030"

print (a > b)
print (b > a)
print (b == a)

#Exercice4

e = 'Luis'
f = ' Goncalves'
g = ' * '

print (e + f)

#Exerice5

prenom = input("écrivez votre prénom: ")

nom = input("écrivez votre nom: ")

print(prenom + " " + nom)
print(prenom[0] + " " + nom[0])
print('Premiere lettre du nom de famille: ',(nom[0]))

#Exercice6

#Celsius = int(raw_input("Enter a temperature in Celsius: "))
#Fahrenheit = 9.0/5.0 * Celsius + 32
#print "Temperature:", Celsius, "Celsius = ", Fahrenheit, " F"
#Fahrenheit = int(raw_input("Enter a temperature in Fahrenheit: "))
#Celsius = (Fahrenheit - 32) * 5.0/9.0
#print "Temperature:", Fahrenheit, "Fahrenheit = ", Celsius, " C"

celsius = float(input('Quelle est la temperature?: '))

fahrenheit = (celsius * 1.8) + 32 

print(celsius,"C=", fahrenheit, "F")

temperature_fahrenheit = celsius

celsius = (temperature_fahrenheit * 1.8) - 32
print(fahrenheit,"F=", celsius, "C")

#Exercice7

a=input('Entrer une valeur de verite pour a: (entrer False ou True)')
b=input('Entrer une valeur de verite pour b: (entrer False ou True)')
c=input('Entrer une valeur de verite pour c: (entrer False ou True)')

expression_bol=input('Entrer une expression Bolenne avec des "non", "ou", "et", et des parentheses:')
expression_bol.replace('non', 'not')
expression_bol.replace('et', 'and')
expression_bol.replace('ou', 'or')
print (bool(expression_bol))

# test : non (A et B) ou (C et  non A)