# -*- coding: utf-8 -*-
"""td4.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1u57b0o1XEFYN2TXJ_CouPWTkzhiJt4Aa
"""

#Exercice1

from math import pi
def surf_cercle(r):   #variable r pour le rayon
    return pi * r ** 2

surf_cercle(5)

def surf_cercle2(r=1):
    return pi(r2)

surf_cercle2(3)

def vol_boite(L,l,h): #h=hauteur, L=Longueur et l=largueur
    return Llh

vol_boite(3,2,4)

def vol_boite2(x=None,y=None,z=None): #on définie les argument x,y,z et qui par defaut non pas de valeur soit 'None'
    if y==None and z==None: #si y et z non pas de valeur (None)
        return x3
    elif z==None: #si z n'a pas de valeur (None)
        return (x2)y
    else:
        return xyz

vol_boite2(5,6,8)

def remplacement(c1,c2,ch):
    return ch.replace(c1,c2)

remplacement("t","e","sltpd")

#Exercice2

def nb_car(chaine):
    nb_caracteres=0
    for car in chaine:
        if car == " ":
            pass
        else:
            nb_caracteres+=1
    return nb_caracteres

def nb_mots(chaine):
    nb_mot=len(chaine.split())
    return nb_mot

nb_car("bisous")

#Exercice3
def TableMult(n,debut=1,fin=10):
    for x in range(debut,fin+1):
        print((n*x),end=" ")

TableMult(5)

def TableMult2(n,debut=1,fin=10):
    if debut>fin :
        for x in range(debut,fin,-1):
            print((nx),end=" ")
    else:
        for x in range(debut,fin+1):
            print((nx),end=" ")

TableMult2(6)

#Exercice4
def jeu_motus():
    from random import randint
    mots = ["arbre", "grave", "piece", "nuage", "crane", "sonne", "table", "herbe", "ecrou", "mulet"]
    number = randint(0, len(mots) - 1)
    random_word = mots[number]
    word = []
    user = []
    for x in range(len(word)):
        user.append("-")
    print(" ".join(user))
    compteur = 0

    while True:
    compteur += 1
    if compteur == 11:
    break
    else:
    print("try a number : " + str(compteur))
    ask = input("Entrer a letter : ")
    for i in range(len(word)):
    if ask == word[i]:
    user[i] = word[i]
    if user == word:
    print(" ".join(user))
    win = input("Good game! Replay ? y/n ")
    if win == "y":
    jeu_motus()
    else:
    exit()
    else:
    print(" ".join(user))
    replay = input("Game Over... Replay y/n : ")
    if replay == "y":
    jeu_motus()
    jeu_motus()